export const UPDATE_TIME = "UPDATE_TIME";
export const UPDATE_SHOW_TYPE = "UPDATE_SHOW_TYPE";
export const UPDATE_HEADER = "UPDATE_HEADER";
export const UPDATE_ZT_TYPE = "UPDATE_ZT_TYPE";
export const UPDATE_ZT_COUNT = "UPDATE_ZT_COUNT";
export const UPDATE_ZT_HY = "UPDATE_ZT_HY";
export const UPDATE_SLIDE_OPEN = "UPDATE_SLIDE_OPEN";

export const  UPDATE_ZT_TYPE_FULL = 'UPDATE_ZT_TYPE_FULL';
export const  UPDATE_ZT_COUNT_FULL = 'UPDATE_ZT_COUNT_FULL';
export const  UPDATE_ZT_HY_FULL = 'UPDATE_ZT_HY_FULL';

export const UPDATE_LIST = "UPDATE_LIST";
export const UPDATE_LIST_ACTION = "UPDATE_LIST_ACTION";

export const UPDATE_LIST_TODAY = "UPDATE_LIST_TODAY";
export const UPDATE_LIST_TODAY_ACTION = "UPDATE_LIST_TODAY_ACTION";

export const UPDATE_LIST_YESTERDAY = "UPDATE_LIST_YESTERDAY";
export const UPDATE_LIST_YESTERDAY_ACTION = "UPDATE_LIST_YESTERDAY_ACTION";

