export const UPDATE_TIME = "UPDATE_TIME";
export const UPDATE_SHOW_TYPE = "UPDATE_SHOW_TYPE";
export const UPDATE_HEADER = "UPDATE_HEADER";

export const UPDATE_LIST = "UPDATE_LIST";
export const UPDATE_LIST_ACTION = "UPDATE_LIST_ACTION";

export const UPDATE_LIST_TODAY = "UPDATE_LIST_TODAY";
export const UPDATE_LIST_TODAY_ACTION = "UPDATE_LIST_TODAY_ACTION";

export const UPDATE_LIST_YESTERDAY = "UPDATE_LIST_YESTERDAY";
export const UPDATE_LIST_YESTERDAY_ACTION = "UPDATE_LIST_YESTERDAY_ACTION";

